"""Tests for ``GuppyConverter(acquisition_format="csv")``.

Fully synthetic: the raw acquisition is a handful of CSVs written into ``tmp_path`` and the GuPPy
output is generated by ``mock_guppy``, so nothing here touches GIN. That is possible for CSV precisely
because the format is trivial to fabricate -- unlike a TDT tank, which is why the TDT converter tests
live under ``test_on_data`` against a real stubbed session.

Every value is dyadic (an exact binary fraction) so the CSV text round-trips losslessly and the
written data can be compared with ``assert_array_equal`` rather than a tolerance.
"""

from pathlib import Path

import numpy as np
import pandas
import pytest
from pynwb import NWBHDF5IO

from neuroconv.converters import GuppyConverter
from neuroconv.tools.testing import generate_mock_guppy_output_folder
from neuroconv.utils import dict_deep_update

# GuPPy names a CSV store by its filename stem, so these ids are both the storesList entries and the
# files the converter opens. Two recording sites, each with a signal and an isosbestic control.
RECORDING_SITE_TO_STORES = {
    "dms": {"signal": "dms_signal_channel", "control": "dms_control_channel"},
    "dls": {"signal": "dls_signal_channel", "control": "dls_control_channel"},
}
EVENT_STORE_TO_NAME = {
    "reward_ttl": "rewarded_nose_pokes",
    "no_reward_ttl": "unrewarded_nose_pokes",
    "port_ttl": "port_entries",
}

SAMPLING_RATE = 128.0
NUM_SAMPLES = 64
TIMESTAMPS = np.arange(NUM_SAMPLES, dtype=float) / SAMPLING_RATE
# One distinct, exactly representable ramp per store, so a mis-wired column is unmistakable.
STORE_TO_DATA = {
    "dms_signal_channel": np.arange(NUM_SAMPLES, dtype=float) / 4.0,
    "dms_control_channel": np.arange(NUM_SAMPLES, dtype=float) / 8.0 + 100.0,
    "dls_signal_channel": np.arange(NUM_SAMPLES, dtype=float) / 16.0 + 200.0,
    "dls_control_channel": np.arange(NUM_SAMPLES, dtype=float) / 32.0 + 300.0,
}
STORE_TO_EVENT_TIMESTAMPS = {
    "reward_ttl": np.array([0.25, 0.5]),
    "no_reward_ttl": np.array([0.125, 0.375, 0.625]),
    "port_ttl": np.array([0.0625]),
}

EXPECTED_ACQUISITION_INTERFACE_NAMES = {"FiberPhotometry_signal", "FiberPhotometry_control"}
EXPECTED_EVENTS_INTERFACE_NAMES = {"Events_reward_ttl", "Events_no_reward_ttl", "Events_port_ttl"}
EXPECTED_RESPONSE_SERIES_NAMES = {
    "FiberPhotometryResponseSeriesSignal",
    "FiberPhotometryResponseSeriesControl",
}
MERGED_EVENTS_TABLE_NAME = "BehavioralEvents"

# The FiberPhotometry provenance chain is the user's to supply -- no interface fabricates it. Row order
# fixes the acquisition table layout the converter links the GuPPy recording sites to: dms
# signal/control first, then dls, i.e. rows 0-3.
DEVICE_METADATA = {
    "DeviceModels": {
        "optical_fiber_model": {
            "type": "OpticalFiberModel",
            "name": "optical_fiber_model",
            "manufacturer": "Doric Lenses",
            "numerical_aperture": 0.48,
        },
        "excitation_source_model": {
            "type": "ExcitationSourceModel",
            "name": "excitation_source_model",
            "manufacturer": "Doric Lenses",
            "source_type": "LED",
            "excitation_mode": "one-photon",
        },
        "photodetector_model": {
            "type": "PhotodetectorModel",
            "name": "photodetector_model",
            "manufacturer": "Doric Lenses",
            "detector_type": "photodiode",
        },
    },
    "Devices": {
        "optical_fiber_dms": {
            "type": "OpticalFiber",
            "name": "optical_fiber_dms",
            "device_model_metadata_key": "optical_fiber_model",
            "fiber_insertion": {"depth_in_mm": 2.8, "insertion_position_ap_in_mm": 0.8},
        },
        "optical_fiber_dls": {
            "type": "OpticalFiber",
            "name": "optical_fiber_dls",
            "device_model_metadata_key": "optical_fiber_model",
            "fiber_insertion": {"depth_in_mm": 3.5, "insertion_position_ap_in_mm": 0.1},
        },
        "excitation_source_465": {
            "type": "ExcitationSource",
            "name": "excitation_source_465",
            "device_model_metadata_key": "excitation_source_model",
        },
        "excitation_source_405": {
            "type": "ExcitationSource",
            "name": "excitation_source_405",
            "device_model_metadata_key": "excitation_source_model",
        },
        "photodetector": {
            "type": "Photodetector",
            "name": "photodetector",
            "device_model_metadata_key": "photodetector_model",
        },
    },
}
FIBER_PHOTOMETRY_METADATA = {
    "FiberPhotometryIndicators": {
        "gcamp": {"name": "gcamp", "label": "GCaMP7b", "description": "GCaMP7b calcium indicator."},
    },
    "FiberPhotometryTable": {
        "name": "fiber_photometry_table",
        "description": "Dual-site (DMS/DLS) dual-wavelength fiber photometry setup.",
        "rows": {
            "dms_signal": {
                "location": "DMS",
                "excitation_wavelength_in_nm": 465.0,
                "emission_wavelength_in_nm": 525.0,
                "indicator_metadata_key": "gcamp",
                "optical_fiber_metadata_key": "optical_fiber_dms",
                "excitation_source_metadata_key": "excitation_source_465",
                "photodetector_metadata_key": "photodetector",
            },
            "dms_control": {
                "location": "DMS",
                "excitation_wavelength_in_nm": 405.0,
                "emission_wavelength_in_nm": 525.0,
                "indicator_metadata_key": "gcamp",
                "optical_fiber_metadata_key": "optical_fiber_dms",
                "excitation_source_metadata_key": "excitation_source_405",
                "photodetector_metadata_key": "photodetector",
            },
            "dls_signal": {
                "location": "DLS",
                "excitation_wavelength_in_nm": 465.0,
                "emission_wavelength_in_nm": 525.0,
                "indicator_metadata_key": "gcamp",
                "optical_fiber_metadata_key": "optical_fiber_dls",
                "excitation_source_metadata_key": "excitation_source_465",
                "photodetector_metadata_key": "photodetector",
            },
            "dls_control": {
                "location": "DLS",
                "excitation_wavelength_in_nm": 405.0,
                "emission_wavelength_in_nm": 525.0,
                "indicator_metadata_key": "gcamp",
                "optical_fiber_metadata_key": "optical_fiber_dls",
                "excitation_source_metadata_key": "excitation_source_405",
                "photodetector_metadata_key": "photodetector",
            },
        },
    },
}
# Each series names one table row per stacked column, in column order (dms then dls, the storesList
# order the converter stacks in).
SERIES_METADATA = {
    "signal": {
        "fiber_photometry_table_region": ["dms_signal", "dls_signal"],
        "fiber_photometry_table_region_description": "The 465 nm excitation fibers, DMS then DLS.",
    },
    "control": {
        "fiber_photometry_table_region": ["dms_control", "dls_control"],
        "fiber_photometry_table_region_description": "The 405 nm isosbestic control fibers, DMS then DLS.",
    },
}


def write_mock_guppy_csv_acquisition_folder(folder_path):
    """Write the raw CSVs a GuPPy CSV session is processed from, one file per store.

    Channel files carry GuPPy's fixed ``timestamps,data,sampling_rate`` header (the rate appears only on
    the first row, as GuPPy writes it); event files carry a single ``timestamps`` column. All channels
    share one time axis, which the acquisition interface asserts at construction.
    """
    folder_path.mkdir(parents=True, exist_ok=True)
    for store_id, data in STORE_TO_DATA.items():
        sampling_rate_column = [SAMPLING_RATE] + [None] * (NUM_SAMPLES - 1)
        frame = pandas.DataFrame({"timestamps": TIMESTAMPS, "data": data, "sampling_rate": sampling_rate_column})
        frame.to_csv(folder_path / f"{store_id}.csv", index=False)
    for store_id, event_timestamps in STORE_TO_EVENT_TIMESTAMPS.items():
        pandas.DataFrame({"timestamps": event_timestamps}).to_csv(folder_path / f"{store_id}.csv", index=False)
    return folder_path


class TestGuppyConverterCSV:
    @pytest.fixture
    def acquisition_folder(self, tmp_path):
        return write_mock_guppy_csv_acquisition_folder(tmp_path / "session")

    @pytest.fixture
    def guppy_output_folder(self, tmp_path):
        return generate_mock_guppy_output_folder(
            tmp_path / "session_output_1",
            recording_site_to_stores=RECORDING_SITE_TO_STORES,
            event_store_to_name=EVENT_STORE_TO_NAME,
        )

    @pytest.fixture
    def converter(self, acquisition_folder, guppy_output_folder):
        return GuppyConverter(
            fiber_photometry_folder_path=acquisition_folder,
            events_folder_path=acquisition_folder,
            guppy_folder_path=guppy_output_folder,
            acquisition_format="csv",
        )

    @pytest.fixture
    def metadata(self, converter):
        """The converter's metadata with the user-supplied FiberPhotometry provenance chain merged in."""
        metadata = converter.get_metadata()
        metadata = dict_deep_update(metadata, DEVICE_METADATA)
        metadata["FiberPhotometry"] = dict_deep_update(metadata["FiberPhotometry"], FIBER_PHOTOMETRY_METADATA)
        metadata["FiberPhotometry"] = dict_deep_update(metadata["FiberPhotometry"], SERIES_METADATA)
        return metadata

    def test_one_events_interface_per_store(self, converter):
        """CSV stores each event in its own file, so each needs its own interface (TDT needs only one)."""
        assert set(converter.data_interface_objects) == (
            EXPECTED_ACQUISITION_INTERFACE_NAMES | EXPECTED_EVENTS_INTERFACE_NAMES | {"Guppy"}
        )
        assert set(converter._events_interface_names) == EXPECTED_EVENTS_INTERFACE_NAMES

    def test_acquisition_interfaces_read_the_stores_guppy_listed(self, converter):
        """Each role interface opens one CSV per recording site, in storesList order."""
        signal_interface = converter.data_interface_objects["FiberPhotometry_signal"]
        control_interface = converter.data_interface_objects["FiberPhotometry_control"]
        assert [Path(path).stem for path in signal_interface._file_paths] == [
            "dms_signal_channel",
            "dls_signal_channel",
        ]
        assert [Path(path).stem for path in control_interface._file_paths] == [
            "dms_control_channel",
            "dls_control_channel",
        ]

    def test_run_conversion_writes_role_grouped_acquisition(self, converter, metadata, tmp_path):
        """Two series, one per excitation wavelength, each column-stacking both recording sites."""
        nwbfile_path = tmp_path / "guppy_csv.nwb"
        converter.run_conversion(nwbfile_path=str(nwbfile_path), metadata=metadata, overwrite=True)

        with NWBHDF5IO(str(nwbfile_path), "r") as io:
            nwbfile = io.read()
            assert EXPECTED_RESPONSE_SERIES_NAMES == set(nwbfile.acquisition)

            for series_name, store_ids in [
                ("FiberPhotometryResponseSeriesSignal", ["dms_signal_channel", "dls_signal_channel"]),
                ("FiberPhotometryResponseSeriesControl", ["dms_control_channel", "dls_control_channel"]),
            ]:
                series = nwbfile.acquisition[series_name]
                assert series.data.shape == (NUM_SAMPLES, len(store_ids))
                for column, store_id in enumerate(store_ids):
                    np.testing.assert_array_equal(series.data[:, column], STORE_TO_DATA[store_id])

    def test_run_conversion_links_recording_sites_to_their_own_fibers(self, converter, metadata, tmp_path):
        """Each GuPPy recording site's registry row points at that site's two acquisition table rows."""
        nwbfile_path = tmp_path / "guppy_csv_registry.nwb"
        converter.run_conversion(nwbfile_path=str(nwbfile_path), metadata=metadata, overwrite=True)

        with NWBHDF5IO(str(nwbfile_path), "r") as io:
            nwbfile = io.read()
            recording_sites_table = nwbfile.processing["guppy"]["recording_sites"]
            site_to_locations = {
                str(recording_sites_table["recording_site"][row]): list(
                    recording_sites_table["fiber_photometry_table_region"][row]["location"]
                )
                for row in range(len(recording_sites_table.id))
            }
            assert site_to_locations == {"dms": ["DMS", "DMS"], "dls": ["DLS", "DLS"]}

    def test_run_conversion_merges_every_event_file_into_one_table(self, converter, metadata, tmp_path):
        """The per-store interfaces all write into one BehavioralEvents table, named as GuPPy named them."""
        nwbfile_path = tmp_path / "guppy_csv_events.nwb"
        converter.run_conversion(nwbfile_path=str(nwbfile_path), metadata=metadata, overwrite=True)

        with NWBHDF5IO(str(nwbfile_path), "r") as io:
            nwbfile = io.read()
            assert set(nwbfile.events) == {MERGED_EVENTS_TABLE_NAME}
            events_dataframe = nwbfile.events[MERGED_EVENTS_TABLE_NAME].to_dataframe()

            for store_id, event_name in EVENT_STORE_TO_NAME.items():
                matching = events_dataframe[events_dataframe.event_type == event_name]
                np.testing.assert_array_equal(
                    np.sort(matching.timestamp.to_numpy()), STORE_TO_EVENT_TIMESTAMPS[store_id]
                )
            # The merged table is globally time-sorted, not grouped by contributing interface.
            timestamps = events_dataframe.timestamp.to_numpy()
            np.testing.assert_array_equal(timestamps, np.sort(timestamps))

    def test_guppy_events_registry_references_the_merged_rows(self, converter, metadata, tmp_path):
        """Each GuppyEventsTable row points at its event type's occurrence rows in the merged table."""
        nwbfile_path = tmp_path / "guppy_csv_event_registry.nwb"
        converter.run_conversion(nwbfile_path=str(nwbfile_path), metadata=metadata, overwrite=True)

        with NWBHDF5IO(str(nwbfile_path), "r") as io:
            nwbfile = io.read()
            events_table = nwbfile.processing["guppy"]["events"]
            for row in range(len(events_table.id)):
                event_name = str(events_table["event_name"][row])
                referenced = events_table["events"][row]
                assert set(referenced["event_type"]) == {event_name}
                store_id = next(store for store, name in EVENT_STORE_TO_NAME.items() if name == event_name)
                assert len(referenced) == len(STORE_TO_EVENT_TIMESTAMPS[store_id])

    def test_missing_store_file_raises(self, acquisition_folder, guppy_output_folder):
        """A store GuPPy listed whose CSV is absent fails at construction rather than silently."""
        (acquisition_folder / "dls_signal_channel.csv").unlink()
        with pytest.raises(ValueError, match="dls_signal_channel.csv"):
            GuppyConverter(
                fiber_photometry_folder_path=acquisition_folder,
                events_folder_path=acquisition_folder,
                guppy_folder_path=guppy_output_folder,
                acquisition_format="csv",
            )
