import datetime
import json
import warnings
from pathlib import Path
from typing import Optional

import numpy as np
from dateutil.parser import parse as dateparse
from pydantic import FilePath, validate_call

from ..baseimagingextractorinterface import BaseImagingExtractorInterface
from ....utils import DeepDict


class ScanImageImagingInterface(BaseImagingExtractorInterface):
    """Interface for reading TIFF files produced via ScanImage software.

    This interface is designed to handle the structure of ScanImage TIFF files, which can contain
    multi-channel and both planar and volumetric data. It supports both single-file and multi-file
    datasets generated by ScanImage in various acquisition modes (grab, focus, loop).

    ScanImage is a software package for controlling laser scanning microscopes, particularly for
    two-photon and multi-photon imaging. The interface extracts imaging data and metadata from
    ScanImage TIFF files and converts them to NWB format.

    Key features:

    * Handles multi-channel data with channel selection
    * Supports volumetric (multi-plane) imaging data
    * Automatically detects and loads multi-file datasets based on ScanImage naming conventions
    * Extracts and provides access to ScanImage metadata
    * Efficiently retrieves frames using lazy loading
    * Handles flyback frames in volumetric data
    """

    display_name = "ScanImage Imaging"
    associated_suffixes = (".tif", ".tiff")
    info = "Interface for ScanImage TIFF files."

    @validate_call
    def __init__(
        self,
        file_path: Optional[FilePath] = None,
        *args,  # TODO: change to * (keyword only) on or after August 2026
        channel_name: Optional[str] = None,
        slice_sample: Optional[int] = None,
        plane_index: Optional[int] = None,
        file_paths: Optional[list[FilePath]] = None,
        interleave_slice_samples: Optional[bool] = None,
        verbose: bool = False,
        metadata_key: str | None = None,
    ):
        """
        Parameters
        ----------
        file_path : FilePath, optional
            Path to the ScanImage TIFF file. If this is part of a multi-file series, this should be the first file.
            Either `file_path` or `file_paths` must be provided.
        metadata_key : str, optional
            Metadata key for this interface. When None, defaults to a key derived from
            ``channel_name`` and ``plane_index`` (e.g., ``scan_image_imaging_channel_1_plane_0``).
        channel_name : str, optional
            Name of the channel to extract (e.g., "Channel 1", "Channel 2").

            - If None and only one channel is available, that channel will be used.
            - If None and multiple channels are available, an error will be raised.
            - Use `get_available_channels(file_path)` to see available channels before creating the interface.
        slice_sample : int, optional
            Controls how to handle multiple frames per slice in volumetric data:
            ScanImage data can contain multiple frames for a single plane. Use this to
            select a specific frame from each slice. if None, this will throw an error.
            Select a slice sample or set `interleave_slice_samples` to True to interleave
            all the slice samples as separate volumes/samples. Note that this will scramble the
            acquisition order of the frames.
            This parameter has no effect when frames_per_slice = 1.
        plane_index : int, optional
            Must be between ``0`` and ``num_planes-1``. Used to extract a specific plane from volumetric data.
            When provided:

            - The resulting extractor will be planar
            - Each sample will contain only data for the specified plane
            - This parameter has no effect on planar (non-volumetric) data.
        file_paths : list[Path | str], optional
            List of file paths to use. This is an escape value that can be used
            in case the automatic file detection doesn't work correctly and can be used
            to override the automatic file detection.
            This is useful when:

            - Automatic detection doesn't work correctly
            - You need to specify a custom subset of files
            - You need to control the exact order of files
            The file paths must be provided in the temporal order of the frames in the dataset.
        interleave_slice_samples : bool, optional
            Controls whether to interleave all slice samples as separate time points when frames_per_slice > 1:

            - If True: Interleaves all slice samples as separate time points, increasing the effective
            number of samples by frames_per_slice. This treats each slice_sample as a distinct sample.
            - If False: Requires a specific slice_sample to be provided when frames_per_slice > 1.
            - This parameter has no effect when ``frames_per_slice = 1`` or when ``slice_sample`` is provided.
            - Default is False.
        verbose : bool, default: False
            If True, will print detailed information about the interface initialization process.
        """
        # Handle deprecated positional arguments
        if args:
            parameter_names = [
                "channel_name",
                "slice_sample",
                "plane_index",
                "file_paths",
                "interleave_slice_samples",
                "verbose",
            ]
            num_positional_args_before_args = 1  # file_path
            if len(args) > len(parameter_names):
                raise TypeError(
                    f"__init__() takes at most {len(parameter_names) + num_positional_args_before_args + 1} positional arguments but "
                    f"{len(args) + num_positional_args_before_args + 1} were given. "
                    "Note: Positional arguments are deprecated and will be removed on or after August 2026. "
                    "Please use keyword arguments."
                )
            positional_values = dict(zip(parameter_names, args))
            passed_as_positional = list(positional_values.keys())
            warnings.warn(
                f"Passing arguments positionally to ScanImageImagingInterface.__init__() is deprecated "
                f"and will be removed on or after August 2026. "
                f"The following arguments were passed positionally: {passed_as_positional}. "
                "Please use keyword arguments instead.",
                FutureWarning,
                stacklevel=2,
            )
            channel_name = positional_values.get("channel_name", channel_name)
            slice_sample = positional_values.get("slice_sample", slice_sample)
            plane_index = positional_values.get("plane_index", plane_index)
            file_paths = positional_values.get("file_paths", file_paths)
            interleave_slice_samples = positional_values.get("interleave_slice_samples", interleave_slice_samples)
            verbose = positional_values.get("verbose", verbose)

        file_paths = [Path(file_path)] if file_path else file_paths
        header_version = self.get_scanimage_version(file_path=file_paths[0])
        if header_version not in [3, 4, 5]:
            raise ValueError(
                f"Unsupported ScanImage version {header_version}. Supported versions are 3, 4, and 5."
                f"Most likely this is a legacy version, use ScanImageLegacyImagingInterface instead."
            )

        if interleave_slice_samples is None:
            interleave_slice_samples = False

        if metadata_key is None:
            parts = ["scan_image_imaging"]
            if channel_name is not None:
                parts.append(channel_name.replace(" ", "_").lower())
            if plane_index is not None:
                parts.append(f"plane_{plane_index}")
            metadata_key = "_".join(parts)

        self.channel_name = channel_name
        self.plane_index = plane_index
        super().__init__(
            file_path=file_path,
            channel_name=channel_name,
            file_paths=file_paths,
            plane_index=plane_index,
            slice_sample=slice_sample,
            interleave_slice_samples=interleave_slice_samples,
            verbose=verbose,
            metadata_key=metadata_key,
        )

        # Make sure the timestamps are available, the extractor caches them
        times = self.imaging_extractor.get_times()
        self.imaging_extractor.set_times(times=times)

    @classmethod
    def get_extractor_class(cls):
        from roiextractors import ScanImageImagingExtractor

        return ScanImageImagingExtractor

    def _initialize_extractor(self, interface_kwargs: dict):
        self.extractor_kwargs = interface_kwargs.copy()
        self.extractor_kwargs.pop("verbose", None)
        self.extractor_kwargs.pop("photon_series_type", None)
        self.extractor_kwargs.pop("metadata_key", None)

        extractor_class = self.get_extractor_class()
        extractor_instance = extractor_class(**self.extractor_kwargs)
        return extractor_instance

    def get_metadata(self, *, use_new_metadata_format: bool = False) -> DeepDict:
        """
        Get metadata for the ScanImage imaging data.

        Parameters
        ----------
        use_new_metadata_format : bool, default: False
            When False, returns the old list-based metadata format (backward compatible).
            When True, returns dict-based metadata with ScanImage provenance.

        Returns
        -------
        DeepDict
            The metadata dictionary containing imaging metadata from the ScanImage files.
            This includes:
            - Session start time extracted from the ScanImage file
            - Device information for the microscope
            - Optical channel configuration
            - Imaging plane details including grid spacing and origin coordinates if available
            - Photon series metadata with scan line rate and other acquisition parameters
        """
        metadata = (
            super().get_metadata()
            if not use_new_metadata_format
            else super().get_metadata(use_new_metadata_format=True)
        )

        session_start_time = self._get_session_start_time()
        if session_start_time:
            metadata["NWBFile"]["session_start_time"] = session_start_time

        if not hasattr(self.imaging_extractor, "_general_metadata"):
            return metadata

        # Extract source fields once from the ScanImage header
        scanimage_metadata = self.imaging_extractor._general_metadata
        frame_data = scanimage_metadata.get("FrameData", {})
        roi_metadata = scanimage_metadata.get("RoiGroups", {})

        version = None
        if "SI.VERSION_MAJOR" in frame_data:
            version = (
                f"{frame_data.get('SI.VERSION_MAJOR', '')}."
                f"{frame_data.get('SI.VERSION_MINOR', '')}."
                f"{frame_data.get('SI.VERSION_UPDATE', '')}"
            )

        scan_line_rate = None
        if "SI.hRoiManager.linePeriod" in frame_data:
            scan_line_rate = 1 / float(frame_data["SI.hRoiManager.linePeriod"])
        elif "SI.hScan2D.scannerFrequency" in frame_data:
            scan_line_rate = frame_data["SI.hScan2D.scannerFrequency"]

        grid_spacing = None  # numpy array in micrometers (from source)
        origin_coords = None  # list/tuple in micrometers (from source)
        if "imagingRoiGroup" in roi_metadata and "rois" in roi_metadata["imagingRoiGroup"]:
            rois = roi_metadata["imagingRoiGroup"]["rois"]
            if isinstance(rois, dict) and "scanfields" in rois:
                scanfields = rois["scanfields"]
                if "sizeXY" in scanfields and "pixelResolutionXY" in scanfields:
                    fov_size_in_um = np.array(scanfields["sizeXY"])
                    frame_dimension = np.array(scanfields["pixelResolutionXY"])
                    grid_spacing = fov_size_in_um / frame_dimension
                if "centerXY" in scanfields:
                    origin_coords = scanfields["centerXY"]

        sampling_frequency = float(self.imaging_extractor.get_sampling_frequency())

        if use_new_metadata_format:
            device_description = "Microscope controlled by ScanImage"
            if version is not None:
                device_description = f"Microscope and acquisition data with ScanImage (version {version})"
            metadata["Devices"] = {
                self.metadata_key: {"description": device_description},
            }

            imaging_plane_entry = {
                "device_metadata_key": self.metadata_key,
                "imaging_rate": sampling_frequency,
            }
            if grid_spacing is not None:
                imaging_plane_entry["grid_spacing"] = (grid_spacing * 1e-6).tolist()
                imaging_plane_entry["grid_spacing_unit"] = "meters"
            if origin_coords is not None:
                imaging_plane_entry["origin_coords"] = [float(c) * 1e-6 for c in origin_coords]
                imaging_plane_entry["origin_coords_unit"] = "meters"

            microscopy_series_entry = {
                "imaging_plane_metadata_key": self.metadata_key,
                "description": f"Imaging data acquired using ScanImage for {self.channel_name}",
            }
            if scan_line_rate is not None:
                microscopy_series_entry["scan_line_rate"] = scan_line_rate

            metadata["Ophys"] = {
                "ImagingPlanes": {self.metadata_key: imaging_plane_entry},
                "MicroscopySeries": {self.metadata_key: microscopy_series_entry},
            }
            return metadata

        # Old list-based format
        device_name = "Microscope"
        metadata["Ophys"]["Device"][0].update(name=device_name, description="Microscope controlled by ScanImage")
        channel_name_string = self.channel_name.replace(" ", "").capitalize()

        optical_channel_name = f"OpticalChannel{channel_name_string}"
        optical_channel_metadata = {
            "name": optical_channel_name,
            "description": "Optical channel from ScanImage acquisition",
            "emission_lambda": np.nan,
        }

        imaging_plane_metadata = metadata["Ophys"]["ImagingPlane"][0]
        plane_index_string = f"Plane{self.plane_index}" if self.plane_index is not None else ""
        imaging_plane_name = f"ImagingPlane{channel_name_string}{plane_index_string}"
        imaging_plane_metadata.update(
            name=imaging_plane_name,
            device=device_name,
            imaging_rate=sampling_frequency,
            description="Imaging plane from ScanImage acquisition",
            optical_channel=[optical_channel_metadata],
        )

        photon_series_key = self.photon_series_type  # "TwoPhotonSeries" or "OnePhotonSeries"
        photon_series_metadata = metadata["Ophys"][photon_series_key][0]
        photon_series_name = f"{photon_series_key}{channel_name_string}{plane_index_string}"
        photon_series_metadata["imaging_plane"] = imaging_plane_name
        photon_series_metadata["name"] = photon_series_name
        photon_series_metadata["description"] = f"Imaging data acquired using ScanImage for {self.channel_name}"

        if scan_line_rate is not None:
            photon_series_metadata.update(scan_line_rate=scan_line_rate)

        if version is not None:
            metadata["Ophys"]["Device"][0][
                "description"
            ] = f"Microscope and acquisition data with ScanImage (version {version})"

        if grid_spacing is not None:
            imaging_plane_metadata.update(grid_spacing=grid_spacing.tolist(), grid_spacing_unit="micrometers")

        if origin_coords is not None:
            imaging_plane_metadata.update(origin_coords=origin_coords, origin_coords_unit="micrometers")

        return metadata

    def _get_session_start_time(self) -> datetime.datetime | None:
        """
        Extract and parse the 'epoch' metadata from a ScanImage TIFF file as the session start time.

        This method opens the first frame of the TIFF file, extracts the 'epoch' field from the
        ImageDescription tag, and parses it into a datetime object.

        Returns
        -------
        datetime
            Parsed datetime from the 'epoch' metadata.

        Raises
        ------
        ValueError
            If 'epoch' metadata is not found in the file.
        """

        from tifffile import TiffReader

        tiff_file_path = self.imaging_extractor.file_path
        with TiffReader(tiff_file_path) as tif:
            image_description = tif.pages[0].tags["ImageDescription"].value

        import re

        match = re.search(r"epoch\s*=\s*\[([^\]]+)\]", image_description)
        if not match:
            raise ValueError(f"'epoch' field not found in {tiff_file_path}")

        epoch_values = match.group(1).split()
        import warnings

        if len(epoch_values) != 6:
            warnings.warn(
                f"Expected 6 values in 'epoch' field, found {len(epoch_values)}: \n" f"Epoch field {epoch_values}."
            )
            return None

        year, month, day, hour, minute, seconds = map(float, epoch_values)
        second_int = int(seconds)
        microsecond = int((seconds - second_int) * 1e6)

        return datetime.datetime(int(year), int(month), int(day), int(hour), int(minute), second_int, microsecond)

    @staticmethod
    def get_scanimage_version(file_path: Path | str) -> int:
        """
        Extract the ScanImage version from a BigTIFF file without validation.

        This method reads the binary header of the TIFF file to determine the ScanImage version
        that produced it. It supports ScanImage versions 3, 4, and 5.

        Parameters
        ----------
        file_path : Path | str
            Path to the ScanImage TIFF file

        Returns
        -------
        int
            ScanImage version number (3, 4, or 5)
        """
        with open(file_path, "rb") as f:
            # Skip the TIFF header (16 bytes) and the Magic Number (4 bytes)
            f.seek(20)

            # Read ScanImage version (4 bytes)
            version_bytes = f.read(4)
            scanimage_version = int.from_bytes(version_bytes, byteorder="little")

            return scanimage_version

    @staticmethod
    def get_available_channels(file_path: Path | str) -> list[str]:
        """
        Get the channel names available in a ScanImage TIFF file.

        This static method extracts the channel names from a ScanImage TIFF file
        without needing to create an interface instance. This is useful for
        determining which channels are available before creating an interface.

        Parameters
        ----------
        file_path : Path | str
            Path to the ScanImage TIFF file.

        Returns
        -------
        list[str]
            List of channel names available in the file (e.g., ["Channel 1", "Channel 2"]).
        """
        from roiextractors import ScanImageImagingExtractor

        return ScanImageImagingExtractor.get_available_channels(file_path=file_path)

    @staticmethod
    def get_available_planes(file_path: Path | str) -> list[str]:
        """
        Get the available plane names from a ScanImage TIFF file.

        This static method determines the number of planes (Z-slices) in a volumetric
        ScanImage dataset without needing to create an interface instance. This is useful
        for determining which planes are available before creating an interface.

        Parameters
        ----------
        file_path : Path | str
            Path to the ScanImage TIFF file.

        Returns
        -------
        list[str]
            List of plane names available in the file. For volumetric data, this will be
            a list of strings representing plane indices (e.g., ["0", "1", "2"]).
        """
        from roiextractors import ScanImageImagingExtractor

        return ScanImageImagingExtractor.get_available_planes(file_path=file_path)


class ScanImageLegacyImagingInterface(BaseImagingExtractorInterface):
    """Interface for reading TIFF files produced via ScanImage v3.8."""

    display_name = "ScanImage Imaging"
    associated_suffixes = (".tif",)
    info = "Interface for ScanImage v3.8 TIFF files."

    @classmethod
    def get_source_schema(cls) -> dict:
        source_schema = super().get_source_schema()
        source_schema["properties"]["file_path"]["description"] = "Path to Tiff file."
        return source_schema

    @classmethod
    def get_extractor_class(cls):
        from roiextractors import ScanImageLegacyImagingExtractor

        return ScanImageLegacyImagingExtractor

    def _initialize_extractor(self, interface_kwargs: dict):
        self.extractor_kwargs = interface_kwargs.copy()
        self.extractor_kwargs.pop("fallback_sampling_frequency", None)
        self.extractor_kwargs.pop("metadata_key", None)
        self.extractor_kwargs["sampling_frequency"] = self.sampling_frequency

        extractor_class = self.get_extractor_class()
        extractor_instance = extractor_class(**self.extractor_kwargs)
        return extractor_instance

    @validate_call
    def __init__(
        self,
        file_path: FilePath,
        *args,  # TODO: change to * (keyword only) on or after August 2026
        fallback_sampling_frequency: float | None = None,
        verbose: bool = False,
        metadata_key: str | None = None,
    ):
        """
        DataInterface for reading Tiff files that are generated by ScanImage v3.8. This interface extracts the metadata
        from the exif of the tiff file.

        Parameters
        ----------
        file_path: FilePath
            Path to tiff file.
        fallback_sampling_frequency: float, optional
            The sampling frequency can usually be extracted from the scanimage metadata in
            exif:ImageDescription:state.acq.frameRate. If not, use this.
        metadata_key : str, optional
            Metadata key for this interface. When None, defaults to "scan_image_legacy_imaging".
        """
        # Handle deprecated positional arguments
        if args:
            parameter_names = [
                "fallback_sampling_frequency",
                "verbose",
            ]
            num_positional_args_before_args = 1  # file_path
            if len(args) > len(parameter_names):
                raise TypeError(
                    f"__init__() takes at most {len(parameter_names) + num_positional_args_before_args + 1} positional arguments but "
                    f"{len(args) + num_positional_args_before_args + 1} were given. "
                    "Note: Positional arguments are deprecated and will be removed on or after August 2026. "
                    "Please use keyword arguments."
                )
            positional_values = dict(zip(parameter_names, args))
            passed_as_positional = list(positional_values.keys())
            warnings.warn(
                f"Passing arguments positionally to ScanImageLegacyImagingInterface.__init__() is deprecated "
                f"and will be removed on or after August 2026. "
                f"The following arguments were passed positionally: {passed_as_positional}. "
                "Please use keyword arguments instead.",
                FutureWarning,
                stacklevel=2,
            )
            fallback_sampling_frequency = positional_values.get(
                "fallback_sampling_frequency", fallback_sampling_frequency
            )
            verbose = positional_values.get("verbose", verbose)

        from roiextractors.extractors.tiffimagingextractors.scanimagetiff_utils import (
            extract_extra_metadata,
        )

        self.image_metadata = extract_extra_metadata(file_path=file_path)

        if "state.acq.frameRate" in self.image_metadata:
            sampling_frequency = float(self.image_metadata["state.acq.frameRate"])
        elif "SI.hRoiManager.scanFrameRate" in self.image_metadata:
            sampling_frequency = float(self.image_metadata["SI.hRoiManager.scanFrameRate"])
        else:
            assert_msg = (
                "sampling frequency not found in image metadata, "
                "input the frequency using the argument `fallback_sampling_frequency`"
            )
            assert fallback_sampling_frequency is not None, assert_msg
            sampling_frequency = fallback_sampling_frequency

        if metadata_key is None:
            metadata_key = "scan_image_legacy_imaging"

        self.sampling_frequency = sampling_frequency
        super().__init__(
            file_path=file_path,
            fallback_sampling_frequency=fallback_sampling_frequency,
            verbose=verbose,
            metadata_key=metadata_key,
        )

    def get_metadata(self, *, use_new_metadata_format: bool = False) -> DeepDict:
        """
        Get metadata for the ScanImage imaging data.

        Parameters
        ----------
        use_new_metadata_format : bool, default: False
            When False, returns the old list-based metadata format (backward compatible).
            When True, returns dict-based metadata with ScanImage provenance keyed by
            ``metadata_key`` under ``Devices``, ``Ophys.ImagingPlanes`` and
            ``Ophys.MicroscopySeries``.

        Returns
        -------
        DeepDict
            Dictionary containing metadata including session start time and device information
            specific to the ScanImage system.
        """
        metadata = (
            super().get_metadata()
            if not use_new_metadata_format
            else super().get_metadata(use_new_metadata_format=True)
        )

        if "state.internal.triggerTimeString" in self.image_metadata:
            extracted_session_start_time = dateparse(self.image_metadata["state.internal.triggerTimeString"])
            metadata["NWBFile"].update(session_start_time=extracted_session_start_time)

        extracted_description = json.dumps(self.image_metadata) if self.image_metadata else None

        if use_new_metadata_format:
            metadata["Devices"] = {
                self.metadata_key: {"description": "Microscope controlled by ScanImage (legacy v3.8)"},
            }
            imaging_plane_entry = {
                "device_metadata_key": self.metadata_key,
                "imaging_rate": float(self.sampling_frequency),
            }
            microscopy_series_entry = {
                "imaging_plane_metadata_key": self.metadata_key,
            }
            if extracted_description is not None:
                microscopy_series_entry["description"] = extracted_description
            metadata["Ophys"] = {
                "ImagingPlanes": {self.metadata_key: imaging_plane_entry},
                "MicroscopySeries": {self.metadata_key: microscopy_series_entry},
            }
        else:
            device_number = 0  # Imaging plane metadata is a list with metadata for each plane
            two_photon_series_metadata = metadata["Ophys"]["TwoPhotonSeries"][device_number]
            if extracted_description is not None:
                two_photon_series_metadata.update(description=extracted_description)

        return metadata


def get_scanimage_major_version(scanimage_metadata: dict) -> str:
    """
    Determine the version of ScanImage that produced the TIFF file.

    Parameters
    ----------
    scanimage_metadata : dict
        Dictionary of metadata extracted from a TIFF file produced via ScanImage.

    Returns
    -------
    version: str
        The version of ScanImage that produced the TIFF file.

    Raises
    ------
    ValueError
        If the ScanImage version could not be determined from metadata.
    """
    if "SI.VERSION_MAJOR" in scanimage_metadata:
        return scanimage_metadata["SI.VERSION_MAJOR"]
    elif "state.software.version" in scanimage_metadata:
        return scanimage_metadata["state.software.version"]

    raise ValueError("ScanImage version could not be determined from metadata.")
