name: Documentation
description: Is the documentation of something missing, unclear, or lacking? This is the place.
title: "[Documentation]: "
labels: "documentation"
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your suggestion!

        We welcome any ideas about how to make **NeuroConv** better for the community.

        Please keep in mind that new or improved documentation may not get implemented immediately.
  - type: textarea
    id: summary
    attributes:
      label: What would you like changed or added to the documentation and why?
      description: Do you have any suggestions for the documents?
    validations:
      required: true
  - type: dropdown
    id: interest
    attributes:
      label: Do you have any interest in helping write or edit the documentation?
      description: |
        We appreciate any help you can offer!

        For information on how to contribute, please refer to our [developer guide](https://neuroconv.readthedocs.io/en/main/developer_guide.html).
      options:
        - Yes.
        - Yes, but I would need guidance.
        - No.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
          required: true
        - label: Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?
          required: true
