name: Feature Request
description: Suggest an idea for a brand new feature, or a change to an existing one.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your suggestion!

        We welcome any ideas about how to make **NeuroConv** better for the community.

        Please keep in mind that new features may not get implemented immediately.
  - type: textarea
    id: summary
    attributes:
      label: What would you like to see added to NeuroConv?
      description: |
        What are you trying to achieve with **NeuroConv**?

        Is this a more convenient way to do something that is already possible, or is a workaround currently unfeasible?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
  - type: dropdown
    id: interest
    attributes:
      label: Do you have any interest in helping implement the feature?
      description: |
        We appreciate any help you can offer!

        For information on how to contribute, please refer to our [developer guide](https://neuroconv.readthedocs.io/en/main/developer_guide.html).
      options:
        - Yes.
        - Yes, but I would need guidance.
        - No.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
          required: true
        - label: Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?
          required: true
