"""Authors: Cody Baker and Ben Dichter."""
from abc import abstractmethod, ABC
import uuid
from typing import Optional, Dict, Any

from pynwb import NWBFile
from pydantic.schema import model_schema

from .utils import get_base_schema, get_schema_from_method_signature, get_pydantic_model_from_method_signature


class BaseDataInterface(ABC):
    """
    Abstract class defining the structure of all DataInterfaces.

    Attributes
    ----------
    source_data : dict
        Structure of input arguments used in upstream initialization.
    source_data_to_validate : dict, default: None
        If the input arguments for the downstream __init__ of the interface differ from upstream structure
        this can be specified to clarify which structure is to be validated.

    """

    source_data: Dict[str, Any]
    source_data_to_validate: Optional[Dict[str, Any]] = None

    @classmethod
    def get_source_model(cls):
        """Infer the Pydantic model for the source_data from the method signature (annotation typing)."""
        return get_pydantic_model_from_method_signature(function=cls.__init__, exclude=["self"])

    @classmethod
    def get_source_schema(cls):
        """Infer the JSON schema for the source_data from the method signature (annotation typing)."""
        return model_schema(cls.get_source_model())

    @classmethod
    def get_conversion_options_schema(cls):
        """Infer the JSON schema for the conversion options from the method signature (annotation typing)."""
        return get_schema_from_method_signature(cls.run_conversion, exclude=["nwbfile", "metadata"])

    def _validate_source(self, source_data_to_validate: dict):
        self.get_source_model().parse_obj(obj=source_data_to_validate)

    def __init__(self, **source_data):
        self.source_data = source_data
        self.source_data_to_validate = self.source_data_to_validate or self.source_data
        self._validate_source(source_data_to_validate=self.source_data_to_validate)

    def get_metadata_schema(self):
        """Retrieve JSON schema for metadata."""
        metadata_schema = get_base_schema(
            id_="metadata.schema.json",
            root=True,
            title="Metadata",
            description="Schema for the metadata",
            version="0.1.0",
        )
        return metadata_schema

    def get_metadata(self):
        """Child DataInterface classes should override this to match their metadata."""
        metadata = dict(
            NWBFile=dict(
                session_description="Auto-generated by neuroconv",
                identifier=str(uuid.uuid4()),
            ),
        )

        return metadata

    def get_conversion_options(self):
        """Child DataInterface classes should override this to match their conversion options."""
        return dict()

    @abstractmethod
    def run_conversion(
        self,
        nwbfile_path: Optional[str] = None,
        nwbfile: Optional[NWBFile] = None,
        metadata: Optional[dict] = None,
        overwrite: bool = False,
        **conversion_options,
    ):
        """
        Run the NWB conversion for the instantiated data interface.

        Parameters
        ----------
        nwbfile_path: FilePathType
            Path for where to write or load (if overwrite=False) the NWBFile.
            If specified, the context will always write to this location.
        nwbfile: NWBFile, optional
            An in-memory NWBFile object to write to the location.
        metadata: dict, optional
            Metadata dictionary with information used to create the NWBFile when one does not exist or overwrite=True.
        overwrite: bool, optional
            Whether or not to overwrite the NWBFile if one exists at the nwbfile_path.
            The default is False (append mode).
        verbose: bool, optional
            If 'nwbfile_path' is specified, informs user after a successful write operation.
            The default is True.
        """

        raise NotImplementedError("The run_conversion method for this DataInterface has not been defined!")
