FROM rclone/rclone:latest
RUN $CONFIG_STREAM > ./rclone.conf
RUN $RCLONE_COMMANNDS

FROM ghcr.io/catalystneuro/neuroconv:latest
LABEL org.opencontainers.image.source=https://github.com/catalystneuro/neuroconv_with_rclone
ENV YAML_FILE /usr/local/bin/this_image_yaml_conversion.yml
RUN $YAML_STREAM > $YAML_FILE
ENTRYPOINT neuroconv $YAML_FILE --upload-to-dandiset $DANDISET_ID
