name: Install Wine
description: Quickly install Wine for Linux and macOS runners

runs:
  using: composite
  steps:
    # -------- Linux --------
    - name: Install Wine (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -qq
        sudo apt-get install -yqq wine         # pulls 32-bit libs automatically

    # -------- macOS --------
    - name: Install Wine (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # Apple-Silicon machines: make sure Rosetta exists, but ignore "already installed"
        [[ $(uname -m) == arm64 ]] && \
          softwareupdate --install-rosetta --agree-to-license || true

        # Core runtime pieces
        brew install --cask xquartz            # X11 for Wine GUI apps
        brew tap gcenx/wine
        brew install --cask --no-quarantine gcenx/wine/wine-crossover
        wine --version || echo "Wine installed as an app bundle"

    # -------- Windows --------
    - name: Skip on Windows
      if: runner.os == 'Windows'
      shell: bash
      run: echo "Wine not required on Windows runner."
