name: Upload Docker Image of Latest Release to GHCR

on:
  workflow_run:
    workflows: [auto-publish]
    types: [completed]
  workflow_dispatch:

jobs:
  release-image:
    name: Release NeuroConv Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grab version from release tag
        run: |
          git fetch --prune --unshallow --tags
          tags="$(git tag --list)"
          latest_tag=${tags: -6 : 6}
          echo "latest_tag=$latest_tag" >> "$GITHUB_ENV"
      - name: Printout parsed version for GitHub Action log
        run: echo "$latest_tag"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_UPLOADER_USERNAME }}
          password: ${{ secrets.DOCKER_UPLOADER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true  # Push is a shorthand for --output=type=registry
          tags: ghcr.io/CatalystNeuro/NeuroConv:$latest_tag
          context: docker
          file: dockerfiles/neuroconv_developer_build_dockerfile
