name: Build and Upload Docker Image of Rclone With Config to GHCR

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKER_UPLOADER_USERNAME:
        required: true
      DOCKER_UPLOADER_PASSWORD:
        required: true

concurrency:  # Cancel previous workflows on the same pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-image:
    name: Build and Upload Docker Image of Rclone With Config to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_UPLOADER_USERNAME }}
          password: ${{ secrets.DOCKER_UPLOADER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true  # Push is a shorthand for --output=type=registry
          tags: ghcr.io/catalystneuro/rclone_with_config:latest
          context: .
          file: dockerfiles/rclone_with_config
          provenance: false
