name: Check Docstrings
on:
  workflow_dispatch:
  pull_request:

jobs:
  check-docstrings:
    runs-on: ubuntu-latest
    steps:
      - id: check_docstrings
        uses: catalystneuro/.github/.github/actions/check_docstrings@main
        with:
          python-version: '3.10'
          repository: 'catalystneuro/neuroconv'
          package-name: 'neuroconv'
          branch: ${{ github.ref_name }}
