name: Testing External Links Cron Job

on:
  schedule:
    - cron: "0 16 * * *"  # Daily at noon EST

jobs:
  build-and-test:
    name: Testing External Links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install package for API docs
        run: pip install -e .[docs]
      - name: Test External Links
        run: sphinx-build -b linkcheck -D linkcheck_ignore=[] ./docs ./docs/_build/  # The -D overrides the conf.py file to ignore the linkcheck_ignore list
