name: Testing External Links
on:
  pull_request:
  merge_group:
  workflow_call:

jobs:
  build-and-test:
    name: Testing External Links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package for API docs
        run: pip install .[docs]
      - name: Test External Links
        run: sphinx-build -b linkcheck ./docs ./docs/_build/
