name: Testing External Links
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    # Synchronize, open and reopened are the default types for pull request
    # We add ready_for_review to trigger the check for changelog and full tests when ready for review is clicked
  merge_group:
  workflow_dispatch:
  workflow_call:
    inputs:
      allow-failure:
        required: false
        type: boolean
        default: false
    outputs:
      linkcheck_failed:
        description: "Whether the link check failed"
        value: ${{ jobs.build-and-test.outputs.linkcheck_failed }}

jobs:
  build-and-test:
    if: ${{ github.event.pull_request.draft == false }}
    name: Testing External Links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    outputs:
      linkcheck_failed: ${{ steps.set-failure-flag.outputs.failed }}
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package for API docs
        run: pip install .[docs]
      - name: Test External Links
        id: linkcheck
        run: sphinx-build -b linkcheck ./docs ./docs/_build/
        continue-on-error: ${{ inputs.allow-failure }}
      - name: Set failure flag output
        id: set-failure-flag
        run: echo "failed=${{ steps.linkcheck.outcome == 'failure' }}" >> $GITHUB_OUTPUT
